- hosts: localhost
  become: true
  vars:
    neovim_version: "0.10.0"
    user_home: "/home/henry/"
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/aliases.yml
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/docker.yml
