- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
