- hosts: localhost
  become: true
  vars:
    neovim_version: "0.10.0"
    user_home: "/home/henry/"
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
      tags: packages

    - include_tasks: tasks/aliases.yml
      tags: aliases

    - include_tasks: tasks/locale.yml
      tags: locale

    - include_tasks: tasks/users.yml
      tags: users

    - include_tasks: tasks/cron.yml
      tags: cron

    - include_tasks: tasks/neovim.yml
      tags: neovim

    - include_tasks: tasks/docker.yml
      tags: docker
